[package]
name = "redis_pool"
version = "0.2.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a redis client and cluster client pools."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["Redis", "Pool", "tokio"]
repository = "https://github.com/AscendingCreations/RedisPool"

[features]
cluster = ["redis/cluster-async"]

[dependencies]
tokio = { version = "1.32.0", features = ["sync"] }
async-trait = "0.1.71"
tracing = "0.1.37"
thiserror = "1.0.43"
redis = { version = "0.23.3", features = ["aio", "tokio-comp", "cluster-async"]}
crossbeam-queue = "0.3.8"

[dev-dependencies]
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros", "process", "test-util", "time"] }
testcontainers = "0.14.0"
anyhow = "1.0"
axum = "0.6"
futures = "0.3.28"
redis_pool = { path = ".", features = ["cluster"]}
serial_test = "0.4"
criterion = { version = "0.4", features = ["html_reports", "async_tokio"] }

[dev-dependencies.uuid]
version = "1.4.1"
features = [ "v4", "fast-rng", "macro-diagnostics" ]

[[bench]]
name = "parallel_throughput"
harness = false

[[bench]]
name = "parallel_latency"
harness = false