static_resources:
  listeners:
    - name: redis_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 6379
      filter_chains:
        - filters:
            - name: envoy.filters.network.redis_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
                stat_prefix: egress_redis
                settings:
                  op_timeout: 5s
                prefix_routes:
                  catch_all_route:
                    cluster: redis_cluster
  clusters:
    - name: redis_cluster
      type: STRICT_DNS # static
      lb_policy: MAGLEV
      connect_timeout: 5s
      load_assignment:
        cluster_name: redis_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 7000
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 7001
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 7002
